site_name: Experimental - GUIDE
repo_name: Experimental

repo_url: https://github.com/Foso/Experimental
site_url: https://foso.github.io/Experimental
site_dir: 'docs'
docs_dir: 'mkdocs'
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'deep-blue'
    accent: 'deep-purple'
  feature:
    tabs: true
nav:
  - 'Jetpack Compose':
      - 'Overview': index.md
      - 'Guides & Samples':
          - 'General':
              - 'Hello World Compose': general/helloworld.md
              - 'Compose Lifecycle': general/compose_lifecycle.md
              - 'How to get Android Context': get_android_context.md
              - 'How to draw on Canvas': general/draw_on_canvas.md
          - 'Foundation':
              - 'Clickable': foundation/clickable.md
              - 'VerticalScroller': foundation/vertical_scroller.md
              - 'HorizontalScroller': foundation/horizontal_scroller.md
              - 'Draggable': foundation/draggable.md
          - 'Core':
              - 'PressGestureDetector': core/pressgesturedetector.md
          - 'Layout':
              - 'Column': Layout/Column.md
              - 'Row': Layout/row.md
          - 'Material':
              - 'Switch': material/switch.md
              - 'Checkbox': material/checkbox.md
              - 'RadioGroup': material/radiogroup.md
              - 'AlertDialog': material/alertdialog.md
      - 'Resources': resources.md

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

