site_name: Experimental - GUIDE
repo_name: Experimental

repo_url: https://github.com/Foso/Experimental
site_url: https://foso.github.io/Experimental
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  palette:
    primary: 'deep-blue'
    accent: 'deep-purple'
  feature:
    tabs: true
nav:
  - 'Jetpack Compose':
      - 'Overview': index.md
      - 'Guides & Samples':
          - 'General':
              - 'Hello World Compose': wiki/general/helloworld.md
              - 'Compose Lifecycle': wiki/general/compose_lifecycle.md
              - 'How to get Android Context': wiki/get_android_context.md
              - 'How to draw on Canvas': wiki/general/draw_on_canvas.md
          - 'Foundation':
              - 'Clickable': wiki/foundation/clickable.md
              - 'VerticalScroller': wiki/foundation/vertical_scroller.md
              - 'HorizontalScroller': wiki/foundation/horizontal_scroller.md
              - 'Draggable': wiki/foundation/draggable.md
          - 'Core':
              - 'PressGestureDetector': wiki/core/pressgesturedetector.md
          - 'Layout':
              - 'Column': wiki/Layout/Column.md
              - 'Row': wiki/Layout/row.md
          - 'Material':
              - 'Switch': wiki/material/switch.md
              - 'Checkbox': wiki/material/checkbox.md
              - 'RadioGroup': wiki/material/radiogroup.md
              - 'AlertDialog': wiki/material/alertdialog.md
      - 'Resources': wiki/resources.md

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

