site_name: Experimental - GUIDE
repo_name: Experimental

repo_url: https://github.com/Foso/Experimental
site_url: https://foso.github.io/Experimental
theme:
  name: 'material'
  palette:
    primary: 'deep-blue'
    accent: 'deep-purple'
  feature:
    tabs: true

nav:
  - 'Overview': index.md
  - 'Column': wiki/Column.md

