name: install bitrise
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive" 
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          curl -fL https://github.com/bitrise-io/bitrise/releases/download/1.48.0/bitrise-$(uname -s)-$(uname -m) > /usr/local/bin/bitrise
          chmod +x /usr/local/bin/bitrise
      - name: Build site
        run: bitrise run test
      
