name: Chuck Norris test workflow

on: 
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: chuck-norris-quote-action
        uses: glav/chuck-norris-quote@v1.0
