# This is a basic workflow to help you get started with Actions

name: testparallel

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ui-test-parallel:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success always"
  A:
    needs: [ui-test-parallel]
    runs-on: ubuntu-latest
    steps:
      - run: echo "success always"
  B:
    needs: [ui-test-parallel]
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "this will never run"
  C:
    needs: [ui-test-parallel]
    runs-on: ubuntu-latest
    steps:
      - run: |
          exho "here to fail"
          exit 1
  post-build-status:
    runs-on: ubuntu-latest
    needs: [A, B, C]
    if: |
      always() &&
      !contains(needs.*.result, 'cancelled')
    # you can add conditions if needed e.g.
    # !contains(needs.*.result, 'failure')
    steps:
      - run: |
          echo "${{ toJSON(needs) }}"
          echo "A: Result ${{ needs.A.result }}"
          echo "B: Result ${{ needs.B.result }}"
          echo "C: Result ${{ needs.C.result }}"
